### ISSUE TITLE
Test with Lite XL

### ISSUE THREAD

**Issue by objeck** [objeck/objeck-lsp#10]
[Refererence](https://github.com/objeck/objeck-lsp/issues/7), most issues should be resolved however that needs to be validated.

**Comment by ghost** [comment]
Do it yourself!

Download and extract https://github.com/lite-xl/lite-xl/releases/download/v2.1.1/lite-xl-v2.1.1-addons-windows-x86_64.zip

Download https://github.com/lite-xl/lite-xl-plugin-manager/releases/download/continuous/lpm.x86_64-windows.exe and rename it to `lpm.exe`

Open `lite-xl/lite-xl.exe` and open Windows Command Prompt on the directory contains `lpm.exe`

Run `lpm install lsp` and proceed to install any dependencies needed. After that setting up lsp is done. Close `lite-xl.exe`.

Now configure lite-xl. Your `init.lua` is on `%userprofile%/.config/lite-xl`. Open it and paste these lines into it:

```
local lspconfig = require "plugins.lsp.config"

---# objeck
--- __Status__: Currently not working
--- __Site__: https://github.com/objeck/objeck-lsp
--- __Installation__: See official website for instructions
lspconfig.objeck = add_lsp {
  name = "objeck-lsp",
  language = "objeck",
  file_patterns = { "%.obs$" },
  command = { "obr", "C:/objeck-lsp/objeck_lsp.obe", "C:/objeck-lsp/objk_apis.json", "stdio" },
  verbose = true
}

-- Activate objeck-lsp
lspconfig.objeck.setup()
```

Remember to modify the paths to objeck-lsp. Open `lite-xl.exe`, use ctrl+shift+c to change to the folder containing your .obs source files. Then open a .obs source file, the server will be started automatically.

p/s: to have syntax highlighting for Objeck source, download `language_objeck.lua` from https://github.com/iqskpduswupkcjqg/lite-xl-objeck-lexer/blob/main/language_objeck.lua and put it on `lite-xl/data/plugins`

**Comment by objeck** [comment]
Thanks, is it working now? If not, do you have debug output from the client console or Objeck server log?

**Comment by ghost** [comment]
> Thanks, is it working now? If not, do you have debug output from the client console or Objeck server log?

I don't want to touch this text editor again! If you want to test objeck-lsp with it please do it yourself!

**Comment by objeck** [comment]
Me neither

**Comment by ghost** [comment]
Thanks to https://github.com/objeck/objeck-lang/issues/240 we no longer have to set the `OBJECK_STDIO` environment variable.
