### ISSUE TITLE
Objeck-lsp failed to work with RJ Texted

### ISSUE THREAD

**Issue by ghost** [objeck/objeck-lsp#13]
I just bought Sublime Text then he said he had objeck-lsp configured but not working :neutral_face: 

https://rj-texted.se/Forum/viewtopic.php?p=18811#p18811

**Comment by objeck** [comment]
Thank you, I suspect the issue is environment related. I do not think the ``OBJECK_LIB_PATH`` environment was set for the library path or ``OBJECK_STDIO`` for binary STDIO communication. Over the weekend, I will download the editor and get it working.

**Comment by rickard67** [comment]
I took some time to test the Objeck language server with RJ TextEd and found an issue with textDocument/didChange notifications.

When the builtin client send a textDocument/didChange notification to the server - it always include whole lines. It just makes it easier to handle and probably safer too.
Think of it as selecting a line by placing the cursor on line 1 and select the entire line by hitting SHIFT+DOWN. The notification looks something like this:

Write to server:
Content-Length: 297

{"jsonrpc": "2.0","method": "textDocument/didChange","params": {"textDocument":{"uri":"file:///C%3A/Users/Rickard/Documents/RJ%20TextEd/LSP/Objeck%20test/hello.obs","version":5},"contentChanges":[{"range":{"start":{"line":7,"character":0},"end":{"line":8,"character":0}},"text":"      abc\r\n"}]}}

But it seems the Objeck language server adds an extra line with this notification. Probably at line 8. And it keeps adding new lines with every didChange notification. So the internal document becomes corrupt.
I've tested RJ TextEd with 20+ language servers, so I don't think I'm doing anything wrong.

Would you mind taking a look at it?

I also added some information in the forum on how to add the server to the program [https://www.rj-texted.se/Forum/viewtopic.php?t=5372&sid=1c1b67992eb81fb567114b65ed95d0a4](url)

Rickard Johansson (RJ TextEd)

**Comment by objeck** [comment]
Thanks, Rickard. I will take a look at the issue this week.

**Comment by objeck** [comment]
I will need to test with RJ TextEd. The "textDocument/didChange" messages I receive from other client does not contain a ``\r``'s. I checked with files that had Windows and Unix line endings. Will look more at this next week.

**Comment by ghost** [comment]
> I will need to test with RJ TextEd. The "textDocument/didChange" messages I receive from other client does not contain a `\r`'s. I checked with files that had Windows and Unix line endings. Will look more at this next week.

So it's the fault of RJ TextEd's LSP Client. I think other language servers just ignored the CR because LF is already enough to indicate a new line. The RJ TextEd's LSP Client expects Windows line endings so it always send CRLFs. You could follow what other language servers do and simply ignore the CR. Please correct me if I was wrong.

**Comment by objeck** [comment]
The LSP specifications states that CRs and LFs should not be counted as line characters. The current server code, ignores LFs only using them to count lines. It treats CRs as normal characters and should be updated to ignore them. This has not been an issue in the past because the other clients do not sent CRs.

**Comment by objeck** [comment]
@rickard67, the LSP server appears to be working okay with the code change to ignore CRs in text. I tested against RJ TextEd build 15.85 for Windows 64-bit.

**Comment by rickard67** [comment]
Thank you @objeck 👍 I'll give it a try when a new release is available for download.

**Comment by ghost** [comment]
Thanks to https://github.com/objeck/objeck-lang/issues/240 we no longer have to set the `OBJECK_STDIO` environment variable.
