### ISSUE TITLE
Is objeck-lsp working fine with Vim?

### ISSUE THREAD

**Issue by ghost** [objeck/objeck-lsp#14]
I want to advertise Objeck to some Vim users. But first, I think I should make sure that objeck-lsp is working fine with Vim. The problem is, I personally don't use Vim and know nothing about it other than how to quit it.

**Comment by objeck** [comment]
Related to #14

**Comment by ghost** [comment]
> Related to #14

This is #14! Did you mean #15? #15 is about syntax highlighting. This is about LSP.
