### ISSUE TITLE
Do you still test objeck-lsp on Emacs?

### ISSUE THREAD

**Issue by ghost** [objeck/objeck-lsp#16]
Well, I found that there is not even a syntax highlighting file for Emacs.

**Comment by objeck** [comment]
No, I do not require Emacs on Linux or macOS nowadays. Most of the coding is done in vi and Sublime. However, early development was done on Emacs across hosts.

**Comment by ghost** [comment]
> No, I do not require Emacs on Linux or macOS nowadays. Most of the coding is done in vi and Sublime. However, early development was done on Emacs across hosts.

What do you think about adding a syntax highlighting file for Emacs?

**Comment by objeck** [comment]
Sure, time permitting. I also want to change the VS Code plug-in so that it supports STDIO along with sockets.
