### ISSUE TITLE
Pack `objeck-lsp` using `obb`

### ISSUE THREAD

**Issue by ghost** [objeck/objeck-lsp#24]
Instead of having to run a long `obr` command, only have to use `objeck-lsp-standalone.exe`.

For example, `objeck-lsp-standalone.exe stdio` or `objeck-lsp-standalone.exe 6013 debug`.

The point is to skip the `obr --OBJECK_STDIO=binary objeck_lsp.obe objk_apis.json` part.

**Comment by objeck** [comment]
Will try to add this before the next release, which is this weekend at the latest

**Comment by objeck** [comment]
Thanks for the suggestion. I believe this would require a Windows-specific release. Will look into this more tomorrow.

**Comment by ghost** [comment]
> Thanks for the suggestion. I believe this would require a Windows-specific release. Will look into this more tomorrow.

This idea should also apply to Linux, macOS,... The idea is very simple. The location of `objeck-lsp` is the variable here:

```
obr "<objeck_server_path>/objeck_lsp.obe" <objeck_server_path>/objk_apis.json" stdio
```

To have support for `objeck-lsp` out of the box, LSP clients of code editors allow no such variable.

See: https://github.com/SpartanJ/ecode/issues/203#issuecomment-2004059610

Add `objeck-lsp` to `PATH`, and the binary `objeck-lsp-standalone` is always determined regardless of the location of `objeck-lsp`.
