### ISSUE TITLE
Support stdio

### ISSUE THREAD

**Issue by ghost** [objeck/objeck-lsp#3]
It turned out not only TextAdept and Lite XL (which I believe also use TextAdept's implementation of LSP Client) but also KDE's Kate editor, all of them, only support LSP over stdio. To use Objeck LSP server now, one either has to buy Sublime Text or go with VSCode.

**Comment by ghost** [comment]
The trick to use `netcat` here doesn't work with Objeck LSP: https://github.com/lite-xl/lite-xl-lsp/issues/52#issuecomment-1426885321

**Comment by objeck** [comment]
Objeck does support pipes (via stdio); however, I still need to change the LSP code.

**Comment by objeck** [comment]
I will look into this; in theory, adding studio support should be simple.

**Comment by objeck** [comment]
Implemented
