### ISSUE TITLE
[Tutorial] Setup Kate to use objeck-lsp

### ISSUE THREAD

**Issue by ghost** [objeck/objeck-lsp#5]
Settings -> Configure Kate... -> LSP Client -> User Sever Settings

Create a new settings file with the content:

```
{
    "servers": {
        "objeck": {
            "command": [
                "<objeck_path>/obr.exe",
                "<objeck_server_path>/objeck_lsp.obe",
                "<objeck_server_path>/objk_apis.json",
                "stdio"
            ],
            "url": "https://github.com/objeck/objeck-lsp",
            "highlightingModeRegex": "^Objeck$"
        }
    }
}
```

Note: Kate doesn't support define environment variables like Sublime so the environment variables OBJECK_LIB_PATH and OBJECK_STDIO must be set on Windows.

**Comment by objeck** [comment]
Added to the readme

**Comment by ghost** [comment]
Thanks to https://github.com/objeck/objeck-lang/issues/240 we no longer have to set the `OBJECK_STDIO` environment variable.
