### ISSUE TITLE
The server is very unstable

### ISSUE THREAD

**Issue by PHdrr** [objeck/objeck-lsp#7]
https://github.com/SpartanJ/ecode/discussions/88 https://github.com/SpartanJ/ecode/discussions/89 https://github.com/lite-xl/lite-xl/discussions/1449 https://github.com/lite-xl/lite-xl/discussions/1450 https://github.com/lite-xl/lite-xl/discussions/1451

**Comment by iqskpduswupkcjqg** [comment]
> Please open issues about the LSP plugin in the LSP plugin [repository](https://github.com/lite-xl/lite-xl-lsp).

👍

**Comment by objeck** [comment]
What version should I test against?

**Comment by iahung** [comment]
Lite XL: https://github.com/lite-xl/lite-xl/releases/download/v2.1.1/lite-xl-v2.1.1-addons-windows-x86_64.zip

ECode: https://github.com/SpartanJ/ecode/releases/download/ecode-0.4.7/ecode-windows-0.4.7-x86_64.zip

**Comment by objeck** [comment]
Thanks, need help setting the environment, ping me on [Discord](https://discord.com/invite/qEaCGWR7nb).

**Comment by objeck** [comment]
Thanks, I will set this up over the weekend. I will delay the next release of Objeck until the LSP issues are resolved. I am puzzled that the server is stable with Sublime via STDIO and VS Code via sockets.

**Comment by iqskpduswupkcjqg** [comment]
> Thanks, I will set this up over the weekend. I will delay the next release of Objeck until the LSP issues are resolved. I am puzzled that the server is stable with Sublime via STDIO and VS Code via sockets.

Do you ever think why should we have to care about shitty text editors like TextAdept and Lite XL? I used to be a Linux user before back to Windows 10. I still carry with me the discipline of preferring cross platform software. This is the reason why I tried these text editors in the first place. But now I rethinking it, I'm now only use Windows. Why do I have to care about that? I disliked the attitude of these developers. Too arrogant! They don't care about the users at all.

**Comment by objeck** [comment]
In short, I don't care a lot; however, I am more interested in why the runtime crashes. VS Code is the "gold standard" for LSP support which is what I code for. Personally, I wouldn't say I like VS Code and write all Objeck code in Sublime. The LSP server for Sublime has been fast and stable.

**Comment by iqskpduswupkcjqg** [comment]
I'm never a truly good Linux user as I disliked and never learned how to use Vim or Emacs :smile: Perhaps I will give VSCode a try. It's the most popular now. I have never tried it as I heard people said it's proprietary and bloated :smile:

**Comment by objeck** [comment]
VS Code is too much for me. When I'm coding in C++ are use Emacs on Linux and Visual Studio on windows.

**Comment by objeck** [comment]
Yes, I'm lucky to have such a development platform. However it's loaded with virtual machines and debugging the Objeck runtime uses a lot of memory. I like Sublime because it gets out of my way and let me focus on the code. Visual Studio, not VS Code, is also a good IDE, however I do not utilize the bells and whistles and do not allow it to generate code or do anything fancy.

**Comment by iahung** [comment]
@objeck Do you still testing objeck-lsp with Emacs?

**Comment by iqskpduswupkcjqg** [comment]
> In short, I don't care a lot; however, I am more interested in why the runtime crashes. VS Code is the "gold standard" for LSP support which is what I code for. Personally, I wouldn't say I like VS Code and write all Objeck code in Sublime. The LSP server for Sublime has been fast and stable.

You could test with Zeus IDE as objeck-lsp not only crash with TextAdept or Lite XL. Zeus IDE is easier to setup.

https://github.com/objeck/objeck-lsp/issues/8

**Comment by objeck** [comment]
I am going to pick 4 editors to support

1. Sublime,
2. VS Code,
3. Emacs?
4. VI?

Thoughts? All other editors are a best effort. The last issue I tracked down highlighted a number of limitations in the editor support for the LSP protocol. Coding for editors that provide less support is a low priority. VS has the richest support; however, it is not an editor I use. I've been running Sublime for using STDIO on Windows and VS Code on Windows, macOS, and Linux via sockets without issue.

**Comment by iahung** [comment]
You could exclude Vim, as there are currently no Vim users here. There is currently no syntax highlighting for Objeck on Vim, either. You are very familiar with Emacs, so I think it's reasonable to test objeck-lsp on it. Emacs' LSP Client will be used to test compatibility outside of VS Code and Sublime.

**Comment by PHdrr** [comment]
@objeck Could you test with the ecode editor too? The developer is very friendly, unlike TextAdept and Lite XL. You have talked with him, so you should know. If you could point out the limitations of his LSP client, he will happily fix them.

**Comment by objeck** [comment]
> @objeck Could you test with the ecode editor too? The developer is very friendly, unlike TextAdept and Lite XL. You have talked with him, so you should know. If you could point out the limitations of his LSP client, he will happily fix them.

I will look into it. After working with Zeus, I cannot test/debug every editor. The LSP protocol has many "shortcuts" to support basic editors. I only have time to code around some of them.

**Comment by objeck** [comment]
ecode seems to be working with https://github.com/objeck/objeck-lsp/commit/a7569dfdf8f907ffa97ecea826a7049d2800e756

**Comment by objeck** [comment]
Can someone pull and test Lite XL?
