### ISSUE TITLE
Objeck-lsp failed to work with Zeus IDE

### ISSUE THREAD

**Issue by ghost** [objeck/objeck-lsp#8]
Download the trial version from zeusedit.com. Note: It's not yet support Objeck syntax highlighting.

Options -> Document Types... -> New

Extension: obs

Description: Objeck

Go to Language Server tab:

Program: obr

Arguments:

First textbox: C:/objeck-lsp/objeck_lsp.obe

Second textbox: C:/objeck-lsp/objk_apis.json

Third textbox: stdio

Remember to change the paths to objeck-lsp.

After clicking OK, Zeus IDE is ready to test with objeck-lsp. Open a .obs source file and the language server will be auto started.

**Comment by objeck** [comment]
Looking at this now, Zeus IDE only supports a subset of server features. I will need to dig into this more...

**Comment by objeck** [comment]
I've confirmed that the client supports a subset of the LSP protocol. I'll look into getting to working over the coming days.

**Comment by ghost** [comment]
> I've confirmed that the client supports a subset of the LSP protocol. I'll look into getting to working over the coming days.

You don't need to support any text editor in the world. It's Zeus IDE's fault, not yours. It has immature support for LSP. People should just ditch it and choose another text editor with complete and mature support for LSP. I present Zeus IDE to you only because it's easier to setup. I don't personally use it (as stated, I'm using a free trial version to test LSP). Btw, what do you think if it's the case for TextAdept and Lite XL too? Their support for LSP is incomplete, so they are unable to utilize Objeck-LSP.

p/s: @iahung was right, you should test objeck-lsp with Emacs (or Vim if you could deal with it, I can't, though). They are big open source project, their support for LSP must be more complete and mature than TextAdept and Lite XL. If objeck-lsp doesn't work on Emacs and Vim too, there should be a real compatibility problem.

**Comment by ghost** [comment]
> They are big open source project, their support for LSP must be more complete and mature than TextAdept and Lite XL. If objeck-lsp doesn't work on Emacs and Vim too, there should be a real compatibility problem.

Yes. This is my very logic. Why does objeck-lsp work fine with Kate? Because Kate is a KDE project so the support for LSP should be more complete?

**Comment by ghost** [comment]
@objeck You could contact info@zeusedit.com to have more information about their LSP implementation.

**Comment by objeck** [comment]
I have identified the problem. The issue is that their LSP server. It is not support code diagnostic messages.

**Comment by objeck** [comment]
Not will it allow you to dynamically register workspaces.

**Comment by ghost** [comment]
@objeck So what are you going to do? Close this issue as wont-fix? Because it's their fault not yours.

**Comment by objeck** [comment]
Grr, I found one major issue with the [didChange](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didChange) message, which is critical to making an LSP server function correctly. [Here is](https://github.com/objeck/objeck-lsp/blob/main/server/server.obs#L490) what the LSP expected to parse.

Zeus resends the entire document with each change i.e., keystroke or text update. Editors such as VS Code and Sublime send delta updates. Their syntax is correct; however, at best could be more efficient. I suspect this might be an issue with other such editors.

I like to find out if Objeck is crashing/unstable out generating stack traces; it's the latter for Zeus.

**Comment by objeck** [comment]
The server should be stable now; however, I would/will need to code around the support Zeus provides for the LSP.

**Comment by objeck** [comment]
Also, some of the replies, like completion, are truncated after about 2k reads from the client. Not causing a crash but impacting functionality. So I will save the VM for now and enjoy a beer.

**Comment by ghost** [comment]
> The server should be stable now; however, I would/will need to code around the support Zeus provides for the LSP.

Does Zeus IDE work with Objeck-LSP now? From the tag wontfix, it seems you gave up on it.

**Comment by objeck** [comment]
It does not crash. I can do little about the 2K buffer limit, and the editors desire to send the whole document to the server for every change. LSP functionally in Zeus is mostly for symbols and code completion vs. on-the-fly building and code refactoring.

**Comment by objeck** [comment]
From what I can tell, it is working

**Comment by ghost** [comment]
> From what I can tell, it is working

Yes. I confirmed it was working. But it's unbearably slow. Any Shift+Space to complete a function, e.g., Pri and Shift+Space to suggest Print and PrintLine, took ages. I think it was wise of me to purchase Sublime.

**Comment by ghost** [comment]
Thanks to https://github.com/objeck/objeck-lang/issues/240 we no longer have to set the `OBJECK_STDIO` environment variable.
